### ISSUE TITLE
AttributeError: 'Column' object has no attribute 'update'

### ISSUE THREAD

**Issue by haruhix** [ParisNeo/prompt_translator#30]
after installation when press Enable translation
I get the following errors in the terminal

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 20.8s (prepare environment: 2.8s, launcher: 0.3s, import torch: 6.8s, initialize shared: 0.1s, other imports: 0.4s, list SD models: 0.3s, load scripts: 1.4s, initialize google blockly: 6.7s, create ui: 1.4s, gradio launch: 0.6s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 93.75% GPU memory (15351.00 MB) to load weights, and use 6.25% GPU memory (1024.00 MB) to do matrix computation.
Building translator
Loading generator (this may take few minutes the first time as I need to download the model)
config.json: 100%|########################################################################| 1.43k/1.43k [00:00<?, ?B/s]
model.safetensors: 100%|###########################################################| 2.44G/2.44G [00:11<00:00, 211MB/s]
generation_config.json: 100%|#################################################################| 261/261 [00:00<?, ?B/s]
Loading tokenizer
tokenizer_config.json: 100%|##################################################################| 529/529 [00:00<?, ?B/s]
sentencepiece.bpe.model: 100%|#####################################################| 5.07M/5.07M [00:00<00:00, 265MB/s]
special_tokens_map.json: 100%|################################################################| 649/649 [00:00<?, ?B/s]
Translator is ready
Traceback (most recent call last):
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\venv\Lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\AOD\SD FORGE\stable-diffusion-webui-forge\extensions\prompt_translator\scripts\main.py", line 370, in set_active
    return "# I am ready", self.options.update(visible=True)
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Column' object has no attribute 'update'

**Comment by haruhix** [comment]
fixed it by replacing 2 lines in the main.py file

Changed self.options.update(visible=True) to gr.update(visible=True)
Changed self.options.update(visible=False) to gr.update(visible=False)
